name: Ingest motion data & build web motions

on:
  push:
    paths:
      - 'uploads/**'
      - 'ingest.py'
      - 'ingest_config.yaml'
      - 'tools/**'
      - 'animation/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ingest-and-build
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml openpyxl pyarrow

      - name: Ingest uploads -> db/measurements.csv/.parquet
        run: python ingest.py

      # 若 tools 檔案已經在 repo，這步只做目錄確認；第一次缺檔可在此 cat > 建檔（建議直接放檔即可）
      - name: Ensure motions dir exists
        run: |
          mkdir -p animation/motions
          ls -al animation/motions || true
          ls -al tools || true

      - name: Convert canonical CSV to motion JSON
        run: |
          python tools/csv_to_motion_json.py db/measurements.csv animation/motions

      - name: Build motions index.json
        run: |
          python tools/build_motion_index.py animation/motions > animation/motions/index.json
          echo "Motions index:"
          cat animation/motions/index.json || true

      - name: Commit results (db/ and animation/motions)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add db animation/motions
          git commit -m "Update measurements and motion JSON [skip ci]" || echo "No changes to commit"
          git push
