name: Ingest motion data & build web motions

on:
  workflow_dispatch: {}
  push:
    paths:
      - "uploads/**"
      - "db/measurements.csv"
      - "tools/**"

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # 這裡假設 db/measurements.csv 已由你既有流程產生
      - name: Generate motion JSONs (Mixamo/Xbot mapping)
        run: |
          python tools/csv_to_motion_json.py
          ls -al docs/animation/motions

      - name: Build motion index
        run: |
          python tools/build_motion_index.py
          cat docs/animation/motions/index.json

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/animation/motions/*.json || true
          git commit -m "build: motions & index (Mixamo mapping)" || echo "no changes"
          git push
