name: Ingest motion data

on:
  push:
    paths:
      - 'uploads/**'
      - 'ingest.py'
      - 'ingest_config.yaml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml openpyxl
      - name: Ingest
        run: python ingest.py
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Ingest data [skip ci]" || echo "No changes to commit"
          git push
